# Check: https://github.com/jekyll/jekyll/blob/df8458275de4dc3d0f9b92c5247ff20832d1cc8e/lib/jekyll/configuration.rb
#safe:        false
port: 4000
baseurl:     ""
#url: http://localhost:4000
source:      .
destination: ./_site
#plugins:     ./_plugins
future:      false
lsi:         true
#pygments:    false
#markdown:    kramdown
permalink:   pretty